binary_name = "rayslash"
app_id = "dev.rayan6ms.rayslash"
desktop_entry_name = "dev.rayan6ms.rayslash.desktop"
icon_name = "dev.rayan6ms.rayslash"
metainfo_id = "dev.rayan6ms.rayslash"
metainfo_file = "dev.rayan6ms.rayslash.metainfo.xml"
config_path = "~/.config/rayslash"
state_path = "~/.local/state/rayslash"
cache_path = "~/.cache/rayslash"
runtime_socket_path = "$XDG_RUNTIME_DIR/rayslash.sock"
runtime_socket_fallback = "/tmp/rayslash-$UID/rayslash.sock"
